# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170517_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='adress',
            field=models.CharField(max_length=500),
        ),
    ]
