# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170519_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=500)),
                ('email_ID', models.CharField(max_length=15)),
                ('invoice_no', models.IntegerField()),
                ('item_no', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
