# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170524_0605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill',
            new_name='Product',
        ),
    ]
