# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170524_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount_percent',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sub_total',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_percent',
            field=models.CharField(max_length=200),
        ),
    ]
